### ISSUE TITLE
Script Outline

### ISSUE THREAD

**Issue by jammyness** [jammyness/RenPy_TestforGit#1]
# Hi let's make a game

One of the first steps to making our game would be to have a draft outline of the script :) 
Nata suggested that we make a little game to help women discover what type of engineering they might enjoy!

**Comment by jammyness** [comment]
I want to try tagging @SenzeniMpofu do you happen to know Nata's tag?

**Comment by SenzeniMpofu** [comment]
Hm. No, I don't. 🙃

**Comment by jammyness** [comment]
Well I got you here so that's still a success :) Progress!!

**Comment by jammyness** [comment]
@natalia-piedras test

**Comment by Natalia-Piedras** [comment]
Hello

**Comment by SenzeniMpofu** [comment]
Hurrah!
